version: "3"

services:
        web:
                build:
                        context: ./backend
                        dockerfile: Dockerfile
                command: gunicorn l00moon1ta.wsgi:application --bind 0.0.0.0:8000
                expose:
                        - "8000"
                env_file:
                        - ./backend/.env
        nginx:
                build:
                        context: ./nginx
                        dockerfile: Dockerfile
                ports:
                        - "80:80"
                depends_on:
                        - web
