version: "3"

services:
        back:
                build:
                        context: ./backend
                        dockerfile: Dockerfile
                command: gunicorn l00moon1ta.wsgi:application --bind 0.0.0.0:8000
                ports:
                        - "8000:8000"
                env_file:
                        - ./backend/.env
        web:
                build:
                        context: ./frontend
                        dockerfile: Dockerfile
                ports:
                        - "80:80"
                depends_on:
                        - back
